root: true
parser: "babel-eslint"
parserOptions:
  sourceType: "module"
  module: true
env:
  browser: true
  node: true
  es6: true
  commonjs: true
extends: "eslint:recommended"
plugins:
  - "html"
