default: &default
  adapter:  postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: root
  password:

development:
  <<: *default
  database: ama_development

test:
  <<: *default
  database: ama_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: ama_production
